### ISSUE TITLE
Crash:  'RLMException', reason: ''MyObject' does not have a primary key defined

### ISSUE THREAD

**Issue by RobertGillett** [Kinvey/swift-sdk#353]
### Description
After upgrading to XCode 10.2, Swift 5, and Kinvey 3.22.0 I keep getting this error:
Terminating app due to uncaught exception 'RLMException', reason: ''MyObject' does not have a primary key defined

### Steps to reproduce 
Build with code 10.2 Swift 5

### Kinvey SDK Version
3.22.0

### Tool Versions (XCode / Swift / iOS / Device)
XCode 10.2, Swift 5

**Comment by RobertGillett** [comment]
overriding the primary key when defining the entity seems to fix the issue    

override static func primaryKey() -> String? {
        return "entityId"
    }

**Comment by heyzooi** [comment]
Hi @RobertGillett we are working to fix this and release a new version soon

**Comment by heyzooi** [comment]
@RobertGillett the latest version 3.23.0 is now available and should solve this issue.

**Comment by RobertGillett** [comment]
@heyzooi  I'm receiving build errors. Please see screenshot below.
![Screen Shot 2019-04-16 at 11 28 45 AM](https://user-images.githubusercontent.com/43982205/56235093-8c9dce80-603b-11e9-8d89-b624ca5a2813.png)

**Comment by RobertGillett** [comment]
Unwrapping the values causes a crash

**Comment by heyzooi** [comment]
if you are using CocoaPods make sure CocoaPods is compiling Kinvey using Swift 5

**Comment by RobertGillett** [comment]
@heyzooi Thank you! That was the issue
