### ISSUE TITLE
PubNub dependency out of date

### ISSUE THREAD

**Issue by grantat** [Kinvey/swift-sdk#366]
### Description

PubNub version 4.9.0 is being used for pods, kinvey version 3.23.0. Can't build the project with PubNub because of a dependency issue on the library's variable `stripMobilePayload`.

A suggested fix is to update the .podspec to the specific appropriate dependency versions.

### Steps to reproduce 

1. Create a new project.
2. Create a Podfile and add Kinvey to Podfile project target
3. Pod install
4. Attempt to build the project once workspace created.

### Kinvey SDK Version

3.23.0 to most recent release

### Tool Versions (XCode / Swift / iOS / Device)

Xcode 10.2 / Swift 5 / iOS 12.2

**Comment by heyzooi** [comment]
#367 should fix this issue

**Comment by heyzooi** [comment]
fixed by version `3.27.0`, please try again
