### ISSUE TITLE
Unable to use Swift Package Manager with v4.1.1

### ISSUE THREAD

**Issue by tzuhaohuang** [Kinvey/swift-sdk#377]
### Description

I tried to use Swift Package Manager to add dependency for Kinvey iOS SDK v4.1.1 and it showed the error message of containing incompatible dependencies.

### Steps to reproduce 

In Xcode 11.2.1, File -> Swift Packages -> Add Package Dependency -> Paste https://github.com/Kinvey/swift-sdk.git -> Error shown

### Kinvey SDK Version
4.1.1 for Swift Package Manager

### Tool Versions (XCode / Swift / iOS / Device)
XCode 11.2.1
Swift 5

![Screen Shot 2019-12-04 at 11 02 03 AM](https://user-images.githubusercontent.com/18216145/70159478-f92b1380-1686-11ea-8076-ff3234118930.png)

**Comment by tzuhaohuang** [comment]
I just noticed that Swift Package support is still in beta in release note. 
Is there a way to bypass this issue while still using Swift Package to manage my dependencies?
I was unable to use cocoapod to get v4.1.1 unless I specifically get the version from branch 4.1.1.

Thanks

**Comment by ventsislav-georgiev** [comment]
Closing old issue. The project supports being added through SPM as described above.
